#############################################################################
# Makefile for building: SurvivalText
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  SurvivalText.pro
# Template: app
# Command: /Users/gabeorlanski/Qt/5.2.1/clang_64/bin/qmake -spec macx-g++ CONFIG+=x86_64 -o Makefile SurvivalText.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
CXX           = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -std=c++0x -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../../Qt/5.2.1/clang_64/mkspecs/macx-g++ -I. -I../../../../Qt/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../../Qt/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/gabeorlanski/Qt/5.2.1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/gabeorlanski/Qt/5.2.1/clang_64/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/gabeorlanski/Qt/5.2.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		location.cpp \
		structures.cpp \
		shack.cpp \
		loot.cpp \
		choice_enterbuilding.cpp \
		policestation.cpp \
		house.cpp \
		firestation.cpp \
		foodstore.cpp 
OBJECTS       = main.o \
		location.o \
		structures.o \
		shack.o \
		loot.o \
		choice_enterbuilding.o \
		policestation.o \
		house.o \
		firestation.o \
		foodstore.o
DIST          = ../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/g++-base.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/g++-macx.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/macx-g++/qmake.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf \
		SurvivalText.pro \
		SurvivalText.pro
QMAKE_TARGET  = SurvivalText
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SurvivalText

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-std=c++0x \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SurvivalText.pro ../../../../Qt/5.2.1/clang_64/mkspecs/macx-g++/qmake.conf ../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/g++-base.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/g++-macx.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/macx-g++/qmake.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf \
		SurvivalText.pro \
		/Users/gabeorlanski/Qt/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/gabeorlanski/Qt/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-g++ CONFIG+=x86_64 -o Makefile SurvivalText.pro
../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/g++-base.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/g++-macx.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/macx-g++/qmake.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/c++11.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf:
SurvivalText.pro:
/Users/gabeorlanski/Qt/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/gabeorlanski/Qt/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-g++ CONFIG+=x86_64 -o Makefile SurvivalText.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/SurvivalText1.0.0 || mkdir -p .tmp/SurvivalText1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SurvivalText1.0.0/ && $(COPY_FILE) --parents location.hpp structures.hpp shack.hpp loot.hpp choice_enterbuilding.hpp policestation.hpp house.hpp firestation.hpp foodstore.hpp .tmp/SurvivalText1.0.0/ && $(COPY_FILE) --parents main.cpp location.cpp structures.cpp shack.cpp loot.cpp choice_enterbuilding.cpp policestation.cpp house.cpp firestation.cpp foodstore.cpp .tmp/SurvivalText1.0.0/ && (cd `dirname .tmp/SurvivalText1.0.0` && $(TAR) SurvivalText1.0.0.tar SurvivalText1.0.0 && $(COMPRESS) SurvivalText1.0.0.tar) && $(MOVE) `dirname .tmp/SurvivalText1.0.0`/SurvivalText1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SurvivalText1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp location.hpp \
		structures.hpp \
		loot.hpp \
		shack.hpp \
		policestation.hpp \
		firestation.hpp \
		house.hpp \
		foodstore.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

location.o: location.cpp location.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o location.o location.cpp

structures.o: structures.cpp structures.hpp \
		loot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o structures.o structures.cpp

shack.o: shack.cpp shack.hpp \
		structures.hpp \
		loot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shack.o shack.cpp

loot.o: loot.cpp loot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loot.o loot.cpp

choice_enterbuilding.o: choice_enterbuilding.cpp choice_enterbuilding.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o choice_enterbuilding.o choice_enterbuilding.cpp

policestation.o: policestation.cpp policestation.hpp \
		structures.hpp \
		loot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o policestation.o policestation.cpp

house.o: house.cpp house.hpp \
		structures.hpp \
		loot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o house.o house.cpp

firestation.o: firestation.cpp firestation.hpp \
		structures.hpp \
		loot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o firestation.o firestation.cpp

foodstore.o: foodstore.cpp foodstore.hpp \
		structures.hpp \
		loot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o foodstore.o foodstore.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

